create database retail_mart;
use retail_mart;
rename table `retail_mart`.`supermarket_sales_-_sheet1` to sales;
select * from sales;

select *, str_to_date(`Date`, '%d-%c-%Y') from sales;
update sales
set `Date` = str_to_date(`Date`, '%d-%c-%Y');
select * from sales;
alter table sales
modify column `Date` date;

# 1.	What is the total sales revenue generated by each branch?
select Branch, round(sum(Total),0) as `Total Sales Revenue` from sales
group by Branch;

# 2.	Which product line has the highest number of purchases?
select `Product line`, count(`Invoice ID`) as `No. of Purchases` from sales
group by `Product line`;

# 3.	How does each customer type contribute to total sales? 
select `Customer type`, round(sum(Total),0) as `Contribution to Total Sales` from sales
group by `Customer type`;

# 4.	Which payment method has been used the most for purchases?
select Payment, count(`Invoice Id`) as Transactions, rank() over(order by (count(`Invoice ID`)) desc) as `Rank` from sales
group by Payment;

# 5.	Which branch has the highest average customer rating? 
select Branch, City, round(Avg(Rating),2) as `Average Rating`, rank() over(order by Avg(Rating) desc) as `Rank`  from sales
group by Branch, City
Limit 1;

# 6.	What are the top 5 highest sales transactions recorded? 
select `Invoice ID`, Total as `Total Transaction Value` from sales
order by total desc
limit 5;

# 7.	What is the total revenue generated in each city? 
select City, round(sum(Total),0) as `Total Revenue` from sales
group by City
order by `Total Revenue` desc;

# 8.	Which transactions resulted in a gross income below a specified threshold (e.g., 5)? 
select `Invoice ID`, round(`gross income`,2) as `Gross Income` from sales
where `gross income`< 5
order by `gross income` desc;